# Generated by Django 3.1.1 on 2020-09-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='destination',
            field=models.CharField(default='0', max_length=122),
        ),
        migrations.AddField(
            model_name='contact',
            name='sentence_id',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(default='0', max_length=122),
        ),
        migrations.AddField(
            model_name='contact',
            name='surface_name',
            field=models.CharField(default='0', max_length=122),
        ),
    ]
