# Generated by Django 3.1.1 on 2020-09-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200925_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sentence_id',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
