# Generated by Django 3.1.1 on 2020-09-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200925_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='serial_no',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='unique_source',
            field=models.CharField(default='0', max_length=122),
        ),
    ]
