# Generated by Django 3.1.1 on 2020-09-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200930_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='correct',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
