# Generated by Django 3.1.1 on 2020-09-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact_correct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Wiki',
        ),
    ]
