# Generated by Django 3.1.1 on 2020-10-13 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_downvote_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='downvote',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='downvote_user', to='home.wiki'),
        ),
        migrations.AddField(
            model_name='upvote',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='upvote_user', to='home.wiki'),
        ),
    ]
