# Generated by Django 3.1.1 on 2020-10-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201023_2217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
